// swift-tools-version: 6.0
import PackageDescription

let settings: [SwiftSetting] = [.swiftLanguageMode(.v6), .enableExperimentalFeature("StrictConcurrency")]
let package = Package(
    name: "AgentExecutionKit",
    platforms: [.macOS("27.0")],
    products: [
        .library(name: "AgentExecutionKit", targets: ["AgentExecutionKit"]),
        .library(name: "AgentProcessSupport", targets: ["AgentProcessSupport"]),
        .library(name: "AgentCodexClient", targets: ["AgentCodexClient"]),
        .library(name: "AgentClaudeProtocol", targets: ["AgentClaudeProtocol"]),
        .library(name: "AgentClaudeControl", targets: ["AgentClaudeControl"]),
        .library(name: "AgentClaudeLifecycle", targets: ["AgentClaudeLifecycle"]),
        .library(name: "AgentClaudePermissions", targets: ["AgentClaudePermissions"]),
        .library(name: "AgentClaudeSession", targets: ["AgentClaudeSession"]),
        .library(name: "AgentClaudeEvents", targets: ["AgentClaudeEvents"]),
        .library(name: "AgentClaudeMetadata", targets: ["AgentClaudeMetadata"]),
        .library(name: "AgentClaudeContent", targets: ["AgentClaudeContent"]),
        .library(name: "AgentClaudeConnection", targets: ["AgentClaudeConnection"]),
        .library(name: "AgentClaudeExecution", targets: ["AgentClaudeExecution"]),
        .library(name: "AgentClaudeLaunch", targets: ["AgentClaudeLaunch"]),
        .library(name: "AgentClaudeCapabilities", targets: ["AgentClaudeCapabilities"]),
        .library(name: "AgentClaudeCompatibilityStorage", targets: ["AgentClaudeCompatibilityStorage"]),
        .library(name: "AgentCLIExecution", targets: ["AgentCLIExecution"]),
        .library(name: "AgentHeadlessContracts", targets: ["AgentHeadlessContracts"]),
        .library(name: "AgentCodexExec", targets: ["AgentCodexExec"]),
        .library(name: "AgentClaudeHeadless", targets: ["AgentClaudeHeadless"]),
        .library(name: "AgentGeminiHeadless", targets: ["AgentGeminiHeadless"]),
        .library(name: "AgentACPHeadless", targets: ["AgentACPHeadless"]),
        .library(name: "AgentACPEvents", targets: ["AgentACPEvents"]),
        .library(name: "AgentACPTurnExecution", targets: ["AgentACPTurnExecution"]),
        .library(name: "AgentACPPermissions", targets: ["AgentACPPermissions"]),
        .library(name: "AgentACPSession", targets: ["AgentACPSession"]),
        .library(name: "AgentACPProtocol", targets: ["AgentACPProtocol"]),
        .library(name: "AgentACPConnection", targets: ["AgentACPConnection"]),
        .library(name: "AgentACPRPC", targets: ["AgentACPRPC"]),
        .library(name: "AgentNativeProcessTransport", targets: ["AgentNativeProcessTransport"])
    ],
    dependencies: [
        .package(url: "https://github.com/ajmcclary/ProcessKit.git", .upToNextMinor(from: "0.1.0-beta.5")),
        .package(url: "https://github.com/ajmcclary/AgentRuntimeKit.git", .upToNextMinor(from: "0.1.0-beta.2")),
        .package(url: "https://github.com/ajmcclary/CodexRuntimeKit.git", .upToNextMinor(from: "0.1.0-beta.4")),
        .package(url: "https://github.com/ajmcclary/CodexAppServerKit.git", .upToNextMinor(from: "0.1.0-beta.4")),
        .package(url: "https://github.com/ajmcclary/ClaudeRuntimeKit.git", .upToNextMinor(from: "0.1.0-beta.3")),
        .package(url: "https://github.com/ajmcclary/OpenCodeRuntimeKit.git", .upToNextMinor(from: "0.1.0-beta.4")),
        .package(url: "https://github.com/ajmcclary/AIClientKit.git", .upToNextMinor(from: "0.1.0-beta.9"))
    ],
    targets: [
        .target(name: "AgentProcessSupport", dependencies: [.product(name: "ProcessKit", package: "ProcessKit")], swiftSettings: settings),
        .target(name: "AgentCodexClient", dependencies: [
            .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit"),
            .product(name: "CodexRuntimeKit", package: "CodexRuntimeKit"),
            .product(name: "CodexAppServerKit", package: "CodexAppServerKit"),
            .product(name: "ProcessKit", package: "ProcessKit")
        ], swiftSettings: settings),
        .testTarget(name: "AgentCodexClientTests", dependencies: [
            "AgentCodexClient",
            .product(name: "CodexRuntimeKit", package: "CodexRuntimeKit"),
            .product(name: "CodexAppServerKit", package: "CodexAppServerKit"),
            .product(name: "ProcessKit", package: "ProcessKit")
        ], swiftSettings: settings),
        .target(name: "AgentClaudeProtocol", dependencies: [
            .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit"),
            .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit"),
            .product(name: "AIClientKit", package: "AIClientKit"),
            .product(name: "ProcessStreamFraming", package: "ProcessKit")
        ], swiftSettings: settings),
        .testTarget(name: "AgentClaudeProtocolTests", dependencies: [
            "AgentClaudeProtocol",
            .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit"),
            .product(name: "AIClientKit", package: "AIClientKit")
        ], swiftSettings: settings),
        .target(name: "AgentClaudeControl", dependencies: ["AgentClaudeProtocol"], swiftSettings: settings),
        .testTarget(name: "AgentClaudeControlTests", dependencies: ["AgentClaudeControl", "AgentClaudeProtocol"], swiftSettings: settings),
        .target(name: "AgentClaudeLifecycle", dependencies: [.product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudeLifecycleTests", dependencies: ["AgentClaudeLifecycle", .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentClaudePermissions", dependencies: ["AgentClaudeProtocol", .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudePermissionsTests", dependencies: ["AgentClaudePermissions", "AgentClaudeProtocol", .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentClaudeSession", dependencies: ["AgentClaudeProtocol"], swiftSettings: settings),
        .testTarget(name: "AgentClaudeSessionTests", dependencies: ["AgentClaudeSession", "AgentClaudeProtocol"], swiftSettings: settings),
        .target(name: "AgentClaudeEvents", dependencies: [.product(name: "AIClientKit", package: "AIClientKit"), .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit"), .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudeEventsTests", dependencies: ["AgentClaudeEvents"], swiftSettings: settings),
        .target(name: "AgentClaudeMetadata", dependencies: ["AgentClaudeEvents", "AgentClaudeProtocol"], swiftSettings: settings),
        .testTarget(name: "AgentClaudeMetadataTests", dependencies: ["AgentClaudeMetadata", "AgentClaudeEvents", "AgentClaudeProtocol"], swiftSettings: settings),
        .target(name: "AgentClaudeContent", dependencies: ["AgentClaudeProtocol", "AgentClaudeEvents", .product(name: "AIClientKit", package: "AIClientKit"), .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit"), .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudeContentTests", dependencies: ["AgentClaudeContent", "AgentClaudeProtocol", "AgentClaudeEvents", .product(name: "AIClientKit", package: "AIClientKit"), .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentClaudeConnection", dependencies: ["AgentClaudeProtocol", "AgentNativeProcessTransport", .product(name: "ProcessStreamFraming", package: "ProcessKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudeConnectionTests", dependencies: ["AgentClaudeConnection", "AgentClaudeProtocol", "AgentNativeProcessTransport", .product(name: "ProcessKit", package: "ProcessKit"), .product(name: "ProcessStreamFraming", package: "ProcessKit")], swiftSettings: settings),
        .target(name: "AgentClaudeExecution", dependencies: ["AgentClaudeProtocol", "AgentClaudeContent", "AgentClaudeEvents", "AgentClaudeMetadata", "AgentClaudeSession", "AgentClaudeLifecycle", .product(name: "AIClientKit", package: "AIClientKit"), .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudeExecutionTests", dependencies: ["AgentClaudeExecution", "AgentClaudeProtocol", "AgentClaudeContent", "AgentClaudeEvents", "AgentClaudeSession", "AgentClaudeLifecycle", .product(name: "AIClientKit", package: "AIClientKit"), .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentClaudeLaunch", dependencies: ["AgentClaudeProtocol", .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudeLaunchTests", dependencies: ["AgentClaudeLaunch", "AgentClaudeProtocol", .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentClaudeCapabilities", dependencies: [.product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudeCapabilitiesTests", dependencies: ["AgentClaudeCapabilities", .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentClaudeCompatibilityStorage", dependencies: [.product(name: "AIClientStorage", package: "AIClientKit"), .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudeCompatibilityStorageTests", dependencies: [.product(name: "AIClientStorage", package: "AIClientKit"), "AgentClaudeCompatibilityStorage", .product(name: "ClaudeRuntimeKit", package: "ClaudeRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentCLIExecution", dependencies: [
            .product(name: "ProcessKit", package: "ProcessKit"),
            .product(name: "ProcessStreamFraming", package: "ProcessKit")
        ], swiftSettings: settings),
        .testTarget(name: "AgentCLIExecutionTests", dependencies: ["AgentCLIExecution", .product(name: "ProcessKit", package: "ProcessKit")], swiftSettings: settings),
        .target(name: "AgentHeadlessContracts", dependencies: [.product(name: "AIClientKit", package: "AIClientKit")], swiftSettings: settings),
        .target(name: "AgentCodexExec", dependencies: ["AgentHeadlessContracts", "AgentCLIExecution", .product(name: "AIClientKit", package: "AIClientKit"), .product(name: "ProcessStreamFraming", package: "ProcessKit")], swiftSettings: settings),
        .testTarget(name: "AgentCodexExecTests", dependencies: ["AgentCodexExec", "AgentHeadlessContracts", "AgentCLIExecution", .product(name: "AIClientKit", package: "AIClientKit")], swiftSettings: settings),
        .target(name: "AgentClaudeHeadless", dependencies: ["AgentHeadlessContracts", "AgentCLIExecution", .product(name: "AIClientKit", package: "AIClientKit"), .product(name: "ProcessStreamFraming", package: "ProcessKit")], swiftSettings: settings),
        .testTarget(name: "AgentClaudeHeadlessTests", dependencies: ["AgentClaudeHeadless", "AgentHeadlessContracts", "AgentCLIExecution", "AgentClaudeProtocol", .product(name: "AIClientKit", package: "AIClientKit")], swiftSettings: settings),
        .target(name: "AgentGeminiHeadless", dependencies: ["AgentHeadlessContracts", "AgentCLIExecution", .product(name: "AIClientKit", package: "AIClientKit"), .product(name: "ProcessStreamFraming", package: "ProcessKit")], swiftSettings: settings),
        .testTarget(name: "AgentGeminiHeadlessTests", dependencies: ["AgentGeminiHeadless", "AgentHeadlessContracts", "AgentCLIExecution", .product(name: "AIClientKit", package: "AIClientKit")], swiftSettings: settings),
        .target(name: "AgentACPHeadless", dependencies: ["AgentHeadlessContracts", "AgentACPEvents", .product(name: "AIClientKit", package: "AIClientKit"), .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentACPHeadlessTests", dependencies: ["AgentACPHeadless", "AgentACPEvents", "AgentHeadlessContracts", .product(name: "AIClientKit", package: "AIClientKit"), .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentACPEvents", dependencies: [.product(name: "AIClientKit", package: "AIClientKit"), .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentACPTurnExecution", dependencies: ["AgentACPEvents", "AgentACPProtocol", .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentACPTurnExecutionTests", dependencies: ["AgentACPTurnExecution", "AgentACPEvents", "AgentACPProtocol", .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentACPPermissions", dependencies: ["AgentACPProtocol", "AgentACPRPC", .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentACPPermissionsTests", dependencies: ["AgentACPPermissions", "AgentACPProtocol", "AgentACPRPC", .product(name: "AgentRuntimeKit", package: "AgentRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentACPSession", dependencies: ["AgentACPProtocol", .product(name: "OpenCodeRuntimeKit", package: "OpenCodeRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentACPSessionTests", dependencies: ["AgentACPSession", "AgentACPProtocol", .product(name: "OpenCodeRuntimeKit", package: "OpenCodeRuntimeKit")], swiftSettings: settings),
        .target(name: "AgentACPProtocol", dependencies: ["AgentACPRPC", .product(name: "ProcessStreamFraming", package: "ProcessKit")], swiftSettings: settings),
        .testTarget(name: "AgentACPProtocolTests", dependencies: ["AgentACPProtocol", "AgentACPRPC"], swiftSettings: settings),
        .target(name: "AgentACPConnection", dependencies: ["AgentACPProtocol", "AgentACPRPC", "AgentNativeProcessTransport", .product(name: "ProcessStreamFraming", package: "ProcessKit")], swiftSettings: settings),
        .testTarget(name: "AgentACPConnectionTests", dependencies: ["AgentACPConnection", "AgentACPProtocol", "AgentACPRPC", "AgentNativeProcessTransport", .product(name: "ProcessKit", package: "ProcessKit")], swiftSettings: settings),
        .target(name: "AgentACPRPC", dependencies: [.product(name: "OpenCodeRuntimeKit", package: "OpenCodeRuntimeKit")], swiftSettings: settings),
        .testTarget(name: "AgentACPRPCTests", dependencies: ["AgentACPRPC"], swiftSettings: settings),
        .target(name: "AgentNativeProcessTransport", dependencies: [.product(name: "ProcessKit", package: "ProcessKit")], swiftSettings: settings),
        .testTarget(name: "AgentNativeProcessTransportTests", dependencies: ["AgentNativeProcessTransport", .product(name: "ProcessKit", package: "ProcessKit")], swiftSettings: settings),
        .target(name: "AgentExecutionKit", dependencies: ["AgentProcessSupport"], swiftSettings: settings),
        .testTarget(name: "AgentProcessSupportTests", dependencies: ["AgentProcessSupport"], swiftSettings: settings)
    ]
)
